# Generated by Django 4.0.1 on 2022-01-28 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brokerApp', '0002_alter_cliente_ape_mat_alter_cliente_ape_pat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='tipo_pers',
            field=models.IntegerField(choices=[(1, 'Persona Natural'), (2, 'Empresa')], default='1', verbose_name='Tipo de Cliente'),
        ),
    ]
