# Generated by Django 4.0.3 on 2022-03-30 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brokerApp', '0003_alter_cliente_tipo_pers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='ape_mat',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='ape_pat',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='nombres',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='razon_social',
        ),
        migrations.AddField(
            model_name='cliente',
            name='nombre',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Nombre'),
        ),
    ]
