# Generated by Django 4.0.3 on 2022-03-30 20:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('brokerApp', '0005_alter_cliente_rut'),
    ]

    operations = [
        migrations.CreateModel(
            name='Poliza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nro_poliza', models.CharField(max_length=25, verbose_name='Número de Póliza')),
                ('activo', models.BooleanField(blank=True, default=True, null=True)),
                ('ultima_mod', models.DateTimeField(auto_now=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brokerApp.cliente', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Póliza',
                'verbose_name_plural': 'Pólizas',
            },
        ),
    ]
