# Generated by Django 4.0.3 on 2022-03-30 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brokerApp', '0007_rename_activo_poliza_vigente_poliza_fin_vig_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poliza',
            name='fin_vig',
            field=models.DateField(verbose_name='Fin de Vigencia'),
        ),
        migrations.AlterField(
            model_name='poliza',
            name='ini_vig',
            field=models.DateField(verbose_name='Inicio de Vigencia'),
        ),
    ]
