# Generated by Django 4.0.3 on 2022-03-30 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brokerApp', '0008_alter_poliza_fin_vig_alter_poliza_ini_vig'),
    ]

    operations = [
        migrations.AddField(
            model_name='poliza',
            name='moneda',
            field=models.IntegerField(choices=[(1, 'UF'), (2, 'USD'), (3, 'EUR')], null=True, verbose_name='Moneda'),
        ),
        migrations.AddField(
            model_name='poliza',
            name='producto',
            field=models.IntegerField(choices=[(1, 'Vehículos'), (2, 'Incendio'), (3, 'Pyme'), (4, 'Condominio'), (5, 'RC'), (6, 'Transporte')], null=True, verbose_name='Producto'),
        ),
    ]
