# Generated by Django 4.0.3 on 2022-03-30 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brokerApp', '0009_poliza_moneda_poliza_producto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poliza',
            name='id',
        ),
        migrations.AddField(
            model_name='poliza',
            name='pri_afe',
            field=models.IntegerField(choices=[(1, 'UF'), (2, 'USD'), (3, 'EUR')], null=True, verbose_name='Prima Afecta'),
        ),
        migrations.AddField(
            model_name='poliza',
            name='pri_bru',
            field=models.IntegerField(choices=[(1, 'UF'), (2, 'USD'), (3, 'EUR')], null=True, verbose_name='Prima Bruta'),
        ),
        migrations.AddField(
            model_name='poliza',
            name='pri_exe',
            field=models.IntegerField(choices=[(1, 'UF'), (2, 'USD'), (3, 'EUR')], null=True, verbose_name='Prima Exenta'),
        ),
        migrations.AddField(
            model_name='poliza',
            name='pri_iva',
            field=models.IntegerField(choices=[(1, 'UF'), (2, 'USD'), (3, 'EUR')], null=True, verbose_name='IVA'),
        ),
        migrations.AddField(
            model_name='poliza',
            name='pri_net',
            field=models.IntegerField(choices=[(1, 'UF'), (2, 'USD'), (3, 'EUR')], null=True, verbose_name='Prima Neta'),
        ),
        migrations.AlterField(
            model_name='poliza',
            name='nro_poliza',
            field=models.CharField(max_length=25, primary_key=True, serialize=False, verbose_name='Número de Póliza'),
        ),
    ]
