# Generated by Django 4.0.3 on 2022-03-31 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brokerApp', '0010_remove_poliza_id_poliza_pri_afe_poliza_pri_bru_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poliza',
            name='moneda',
            field=models.IntegerField(choices=[(1, 'UF'), (2, 'USD'), (3, 'EUR')], default=True, null=True, verbose_name='Moneda'),
        ),
        migrations.AlterField(
            model_name='poliza',
            name='pri_afe',
            field=models.DecimalField(decimal_places=2, max_digits=4, null=True, verbose_name='Prima Afecta'),
        ),
        migrations.AlterField(
            model_name='poliza',
            name='pri_bru',
            field=models.DecimalField(decimal_places=2, max_digits=4, null=True, verbose_name='Prima Bruta'),
        ),
        migrations.AlterField(
            model_name='poliza',
            name='pri_exe',
            field=models.DecimalField(decimal_places=2, max_digits=4, null=True, verbose_name='Prima Exenta'),
        ),
        migrations.AlterField(
            model_name='poliza',
            name='pri_iva',
            field=models.DecimalField(decimal_places=2, max_digits=4, null=True, verbose_name='IVA'),
        ),
        migrations.AlterField(
            model_name='poliza',
            name='pri_net',
            field=models.DecimalField(decimal_places=2, max_digits=4, null=True, verbose_name='Prima Neta'),
        ),
    ]
