# Generated by Django 4.0.3 on 2022-03-31 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brokerApp', '0011_alter_poliza_moneda_alter_poliza_pri_afe_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poliza',
            name='pri_afe',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True, verbose_name='Prima Afecta'),
        ),
        migrations.AlterField(
            model_name='poliza',
            name='pri_bru',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True, verbose_name='Prima Bruta'),
        ),
        migrations.AlterField(
            model_name='poliza',
            name='pri_exe',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True, verbose_name='Prima Exenta'),
        ),
        migrations.AlterField(
            model_name='poliza',
            name='pri_iva',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True, verbose_name='IVA'),
        ),
        migrations.AlterField(
            model_name='poliza',
            name='pri_net',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True, verbose_name='Prima Neta'),
        ),
        migrations.AlterField(
            model_name='poliza',
            name='producto',
            field=models.IntegerField(choices=[('Vehículos', 'Vehículos'), ('Incendio', 'Incendio'), ('Pyme', 'Pyme'), ('Condominio', 'Condominio'), ('RC', 'RC'), ('Transporte', 'Transporte')], null=True, verbose_name='Producto'),
        ),
    ]
