# Generated by Django 4.0.3 on 2022-03-31 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brokerApp', '0012_alter_poliza_pri_afe_alter_poliza_pri_bru_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='tipo_pers',
            field=models.IntegerField(choices=[(1, 'Persona Natural'), (2, 'Persona Jurídica')], default='1', verbose_name='Tipo de Cliente'),
        ),
        migrations.AlterField(
            model_name='poliza',
            name='producto',
            field=models.CharField(choices=[('Vehículos', 'Vehículos'), ('Incendio', 'Incendio'), ('Pyme', 'Pyme'), ('Condominio', 'Condominio'), ('RC', 'RC'), ('Transporte', 'Transporte')], max_length=25, null=True, verbose_name='Producto'),
        ),
    ]
