# Generated by Django 4.0.3 on 2022-03-31 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brokerApp', '0013_alter_cliente_tipo_pers_alter_poliza_producto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poliza',
            name='moneda',
            field=models.CharField(choices=[(1, 'UF'), (2, 'USD'), (3, 'EUR')], max_length=25, null=True, verbose_name='Moneda'),
        ),
    ]
